version: "3"

services:
  webserver:
    build: 
      context: ./bin/php8
    container_name: '${COMPOSE_PROJECT_NAME}-api'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    links: 
      - database
    volumes: 
      - ./../app:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
  database:
    build:
      context: "./bin/mariadb106"
    container_name: '${COMPOSE_PROJECT_NAME}-database'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: therootpassword
      MYSQL_DATABASE: populling_names
